name: "Bug report \U0001F41B"
description: Create a report to help us improve
title: ''
labels: ["S-bug"]
assignees: ''
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: List the version(s) of `hyper`, and any relevant hyper dependency (such as `h2` if this is related to HTTP/2).

  - type: textarea
    id: platform
    attributes:
      label: Platform
      description: The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Short summary of the bug
      placeholder: |
        Enter your issue details here.
        One way to structure the description:

        [short summary of the bug]

        I tried this code:

        [code sample that causes the bug]

        I expected to see this happen: [explanation]

        Instead, this happened: [explanation]

          - type: textarea
